### ISSUE TITLE
SpotifySongTagger.exe crashes on loading certain generators

### ISSUE THREAD

**Issue by jhudis** [BenediktAlkin/SongTaggerForSpotify#13]
Some of the generators I've made seem to be corrupted. I can run them just fine, but if I try to actually view the tree in the GUI, the whole GUI crashes. I was able to view them when I made them, but after running them once I can no longer view them without crashing. Not all of my generators do this, just some. There are no errors apparent in the logs. It's hard for me to generate a small example since I'm not exactly sure what causes a generator to become corrupted, but I've attached my current database (with .txt appended to the filename so that GitHub would let me upload it). I would assume anyone opening this database will have the same issue as me, unless there's some cache I could clear or something. I believe the page IDs of the corrupted generators are 1, 3, and 9.
[listen543.sqlite.txt](https://github.com/BenediktAlkin/SongTaggerForSpotify/files/8535060/listen543.sqlite.txt)

**Comment by BenediktAlkin** [comment]
Fixed in new version (v1.2.4)
