### ISSUE TITLE
Desktop app crashes when playing song on Spotify

### ISSUE THREAD

**Issue by jhudis** [BenediktAlkin/SongTaggerForSpotify#30]
If I have the SongTaggerForSpotify desktop app open to the Song Tagger screen and start playing a song on Spotify, the app crashes. Doesn't matter what song I play. Here's the error message in the logs:

`E SP Error in GetArtist (probably couldn't find artist) ArtistId=5V1qsQHdXNm4ZEZHWvFnqQ OuterExceptionMessage=Input string '1320858.0' is not a valid integer. Path 'artists[0].followers.total', line 1, position 140.`

Looks like an easy fix, just need to deal with the ".0" when converting the string to an integer. I assume Spotify changed some API output format...

**Comment by BenediktAlkin** [comment]
You should update your version to 1.2.8; this issue occours with version 1.2.7 but I cant replicate it with 1.2.8
Make sure the "Auto Update" is ticked when you click the 3 dots in the top right
