### ISSUE TITLE
A couple of suggestions for better organization purposes

### ISSUE THREAD

**Issue by TechnicBRICKs** [BenediktAlkin/SongTaggerForSpotify#5]
I've tried you tool and I'm happy you took the effort to address a feature requested by so many Spotify users!
It is already amazing by I found a couple of improvement opportunities that I' like to leave here as suggestions.

1) As a user I'd like to be able to alphabetically sort my created tags.

2) If possible I'd like to see my library which is organized in folders, also appearing organized in the same folders, under "All".
My use case:
I've an huge library, which I organize into year folders (the original song year release, usually not the same year of the album in Spotify).  Then it would be much easier to handle tagging in smaller chunks then all together.
Also as I get new entries added, they go into one specific folder (SoundHound) as this is one way I feed my library with new songs. Again it would be much easier to look at this folder only for new tagging, than picking untagged songs probably among thousands of other songs.

**Comment by BenediktAlkin** [comment]
v1.1.0 just released with the feature to create [Tag Groups](https://raw.githubusercontent.com/BenediktAlkin/SongTaggerForSpotify/main/Examples/QuotaExtensionApplication/SongTagger.png)
