### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by egecavusoglu** [BenediktAlkin/SongTaggerForSpotify#9]
Hello Benedikt. I appreciate your effort for building this app. I made a similar web based app in the past months. I would appreciate if you would take a look and give me feedback. Also, would you be willing to chat about how to develop this idea into something bigger? Take care. You can reach me at egecavusoglu99@gmail.com

Here is the link to the app I built [playlist-maker.vercel.app](https://playlist-maker.vercel.app)

**Comment by BenediktAlkin** [comment]
Looks like a decent app, but it lacks some of the main features that motivated me to make my app.
- play songs from the app (e.g. I don't know ~90% of my songs only from it's name or artist)
- automatic playlist generation

Do you have a concrete idea or what exactly do you mean with something bigger?

**Comment by BenediktAlkin** [comment]
I'm not entirely sure what my part in this is, my app already solves the usecases for organizing music by tags, which is what it was intended to do. Of course there is always room for improvement, but in the grand scheme of things it solves the imo most lacking features of Spotify.

I'm not interested in studying user experience/music listening habits or implementing a business model.

**Comment by egecavusoglu** [comment]
Got you, thank you for responding mate. Take care.
